name: Clippy
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions:
  contents: read

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Install Rust
        run: rustup update stable

      - name: Install Clippy
        run: rustup component add clippy

      - name: Run Clippy
        run: cargo clippy
